### ISSUE TITLE
Problem encountered: Unable to find required Python modules.

### ISSUE THREAD

**Issue by jeremiah** [lkorigin/laniakea#7]
While building Laniakea with meson I get this error;
```
Message: Laniakea requires AppStream GObject introspection data. Please install it to continue.
meson.build:27:4: ERROR: Problem encountered: Unable to find required Python modules.
```
I have python-gobject and python-gi-dev and others but I cannot get past this message. Which python module satisfies this dependency?

**Comment by ximion** [comment]
The message tells you what to do already ;-)
> Laniakea requires AppStream GObject introspection data. Please install it to continue.

=> You'll want to install GIR data for AppStream, on Debian systems that can be done via `sudo apt install gir1.2-appstream-1.0`.
